name: Build and Test

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build-and-test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7", "3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }} and cache dependencies
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: requirements-dev.txt

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies from locked file
        run: python -m pip install -r requirements-dev.txt

      - name: Run linter
        run: flake8 .

      - name: Run tests
        run: pytest --cov uchecker -v
