---
name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  tests:
    name: Tests on ${{ matrix.python-version }}
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ["2.7.18", "3.5.10", "3.6.15", "3.7.16", "3.8.16", "3.9.16", "3.10.11"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel poetry
          poetry config experimental.new-installer false
          poetry install
      - name: Do lint
        run: |
          poetry run flake8 --max-line-length 120 --ignore=E721 .
      - name: Do tests
        run: |
          poetry run pytest --cov uchecker -v

